### ISSUE TITLE
JavaScript crash for completeness charts

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#298]
https://sentry.io/meerkat-who/meerkat/issues/244401357/

```
ReferenceError: drawChartOptionsButtons is not defined
  at eval (eval at <anonymous> (https://iers.moh.gov.jo/static/js/jquery.js:1:14513), <anonymous>:30:1)
  at Function.oe.extend.globalEval (/static/js/jquery.js:1:14513)
  at T (/static/js/jquery.js:1:4634)
  at oe.fn.extend.append (/static/js/jquery.js:2:22023)
  at null.<anonymous> (/static/js/jquery.js:2:23124)
...
(8 additional frame(s) were not displayed)
```

**Comment by jsoppela** [comment]
How much trouble would it be to build exception handling around this? Sentry keeps catching any uncaught exceptions and we could clean up our issue list by catching and logging e.g. timeouts.

**Comment by mixmixmix** [comment]
I don't know how to exception handling in java, I'm afraid. We might look into that for the UI rewrite.

**Comment by jsoppela** [comment]
Closing the issue, this goes to general consolidation tasks
