### ISSUE TITLE
Possible Bootstrap date parsing bug

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#308]
https://sentry.io/meerkat-who/meerkat/issues/248162857/

```
TypeError: defaultDate() Could not parse date parameter: NaN
  at defaultDate (/static/js/bootstrap-datetimepicker.min.js:1:26249)
  at None (/static/js/bootstrap-datetimepicker.min.js:1:22668)
  at each (/static/js/jquery.js:1:14783)
  at options (/static/js/bootstrap-datetimepicker.min.js:1:22575)
  at n (/static/js/bootstrap-datetimepicker.min.js:2:2366)
...
(8 additional frame(s) were not displayed)
```

**Comment by jsoppela** [comment]
Moved to another repo:
https://github.com/meerkat-code/meerkat_issues/issues/9
